filter {
  grok {
    match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:msg}" }
  }
  date {
    match => ["timestamp", "ISO8601"]
  }
}

input {
  file {
    path => "/usr/share/logstash/ingest_data/*"
    mode => "tail"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

output {
  elasticsearch {
    index => "logstash-%{+YYYY.MM.dd}"
    hosts => "${ELASTIC_HOSTS}"
    user => "${ELASTIC_USER}"
    password => "${ELASTIC_PASSWORD}"
	cacert => "/usr/share/logstash/certs/ca/ca.crt"
  }
  stdout { codec => rubydebug }  # zur Kontrolle, was genau reinkommt
}
